Vw integration
vaexio/vaex pull request #1751
Opened 2021-11-29 14:00 UTC by xdssio

A [Vowpal Wabbit](https://vowpalwabbit.org/index.html) integrations with *veax.ml*.

```
import vaex 
import vaex.ml
 
ds = vaex.ml.datasets.load_iris()
ds['class_'] = ds['class_'] + 1  # VW classification starts from 1
model = vaex.ml.vowpalwabbit.VowpalWabbitModel(
    params={'oaa': '3', 'P': 1, 'enable_logging': True},
    features=['sepal_length', 'sepal_width', 'petal_length', 'petal_width'],
    target='class_',
    passes=5)
model.fit(ds)
ds = model.transform(ds) 
ds
#    sepal_length    sepal_width    petal_length    petal_width    class_    vowpalwabbit_prediction
0    5.9             3.0            4.2             1.5            2         2
1    6.1             3.0            4.6             1.4            2         2
2    6.6             2.9            4.6             1.3            2         2

2021-12-12 17:00 UTC, JovanVeljanoski requested changes
Hi! 

Excellent work! We've been wanting to support VW for some time now :). This is great. 
Some comments below, to put it in tip-top shape! But it is very close!

One comment: should we use  `num_epochs` instead of `passes`. It is more consistent with IncrementalPredictor for sklearn and the wrapper for River.

This is my review of the code, I will try this in action and will add additional feedback if needed! 

Good job!

2021-12-12 18:57 UTC, JovanVeljanoski commented
When using the new class and training & predicting/transforming, a lot of logs are printed. There should be an option to suppress  that. Also since the fitting is done in chunks, there should be a progress bar! See `vaex.ml.sklearn.IncrementalPredictor` for an example.

2021-12-14 13:56 UTC, xdssio commented on packages/vaex-ml/vaex/ml/vowpalwabbit.py
> +    def fit(self, df, passes=1, chunk_size=500, partial_fit=False):
Done

2021-12-14 13:58 UTC, xdssio commented on packages/vaex-ml/vaex/ml/vowpalwabbit.py
> +        params = {k: v for k, v in self.params.items() if v is not None}
ok

2021-12-14 14:05 UTC, xdssio commented on packages/vaex-ml/vaex/ml/vowpalwabbit.py
> +    def predict(self, df, **kwargs):
I implemented the logic in predict and used it in __call__.
For the sake of consistency, I moved it the other way around as you suggested.

2021-12-21 15:17 UTC, xdssio commented
> Hi!
> 
> Excellent work! We've been wanting to support VW for some time now :). This is great. Some comments below, to put it in tip-top shape! But it is very close!
> 
> One comment: should we use `num_epochs` instead of `passes`. It is more consistent with IncrementalPredictor for sklearn and the wrapper for River.
> 
> This is my review of the code, I will try this in action and will add additional feedback if needed!
> 
> Good job!

Fixed

2021-12-29 15:44 UTC, xdssio commented
> Hi!
> 
> Excellent work! We've been wanting to support VW for some time now :). This is great. Some comments below, to put it in tip-top shape! But it is very close!
> 
> One comment: should we use `num_epochs` instead of `passes`. It is more consistent with IncrementalPredictor for sklearn and the wrapper for River.
> 
> This is my review of the code, I will try this in action and will add additional feedback if needed!
> 
> Good job!

Think it is done.

2021-12-30 00:32 UTC, JovanVeljanoski commented
Nice! Can you add VW to the CI scripts (requirements). Right now it is not being tested in CI since the package is not installed (and there is this "import or skip" statement). 

Ideally,  it would be nice if testing of VW does not depend on `sklearn`, or in that case you need to wrap sklearn in "import or skip" too, since sklearn is not a dependency of vaex or vaex-ml. Maybe best to write a simple util that calculates accuracy, and remove sklearn (in the test script).

2021-12-31 16:27 UTC, closed without merging